### ISSUE TITLE
Analyzer meta data crash

### ISSUE THREAD

**Issue by JohnCheNey** [taglib/taglib#711]
Hi 
When I use taglib to read the tag info of this file(https://github.com/JohnCheNey/FirstRepo/blob/master/testspace/crashfile.mp3),crash will happen.
It seems like memoryleak turned out when read this file.
If I delete a segment of APE tag frame,the problem solved.
So I wonder if I can add some protect code to prevent this issue?
with kind regards.

**Comment by TsudaKageyu** [comment]
Hi @JohnCheNey, thanks for your report. I have located the cause.

The MP3 file has a huge and corrupt APE tag. The most part of the tag is filled with `0xCC`, and TagLib reads it as a very long string (around 8MB) and tries to handle it as an APE item key. There is no memory leak, but it takes long time.

So I'd like to add a check for the vailidity of APE Item keys. According to Hydrogenaudio (http://wiki.hydrogenaud.io/index.php?title=APE_Tag_Item):
> Item key, can contain ASCII characters from 0x20 (Space) up to 0x7E (Tilde)

Though `0xCC` is not a valid character for an APE item key, TagLib doesn't check it now.

**Comment by TsudaKageyu** [comment]
Fixed, thanks again!

**Comment by JohnCheNey** [comment]
Hi @TsudaKageyu  ,thanks for working on this problem.
As you say there is no memoryleak, but it will cause almost 400MB ram to analyzer this file, isn't it insane?The following log shows the memory cost when read this file.
D/medialibrary( 1908): parserFsItems : url = [/mnt/udisk1/media/crashfile.mp3]
                 total            used            free             shared      buffers
Mem:        988996       551676       437320            0           2508
-/+ buffers:                   549168       439828
Swap:                  0                0                 0
                 total            used            free            shared       buffers
Mem:        988996       650264       338732            0           2508
-/+ buffers:                  647756       341240
Swap:                 0            0            0
                 total            used            free           shared       buffers
Mem:        988996       768684       220312            0          2508
-/+ buffers:                   766176       222820
Swap:            0            0            0
                 total         used         free       shared buffers
Mem:        988996       813980       175016            0 2508
-/+ buffers:             811472       177524
Swap:            0            0            0
             total         used         free       shared buffers
Mem:        988996       912312        76684            0 2508
-/+ buffers:             909804        79192
Swap:            0            0            0
             total         used         free       shared buffers
Mem:        988996       976240        12756            0 1212
-/+ buffers:             975028        13968
Swap:            0            0            0 

Although this may not be a problem, but as for the device I handle with, I have to reduce the memory cost.Now I just throw the data if the tag block is too large, but I think it is not a good solution, cause we can read the right part either.
Since the tag frame and tag values both have length limitation,do we have any better solution?
Thanks again!
With kind regards and looking forward to your reply.

**Comment by TsudaKageyu** [comment]
Hi @JohnCheNey, I committed a patch for this issue. If you can try our latest code on GitHub, you can read your file with much less time and memory consumption, and read the right part of the tag.
If you will find some more problems, feel free to ask me.

**Comment by JohnCheNey** [comment]
Hi @TsudaKageyu , I'v tried the patch you committed,but it still doesn't work for me.
And now I find a solution for my problem.
Maybe there are something inappropriate code in the tstring.cpp file.
  // Converts a UTF-8 string into UTF-16(without BOM/CPU byte order)
  // and copies it to the internal buffer.
  inline void copyFromUTF8(std::wstring &data, const char *s, size_t length)
  {
    data.resize(length);

    if(length > 0) {
      const size_t len = UTF8toUTF16(s, length, &data[0], data.size());
      data.resize(len);
    }
  }
As for the variable TagLib::wstring data,I think we'd better to use a temporary variable instead.
because if we excute data.resize(length) first, the capacity will be more than 'length' forever.
But actually the useful capacity is 'len'.
So I think the following code maybe better?
  inline void copyFromUTF8(std::wstring &data, const char *s, size_t length)
  {
    std::wstring tmp;
    tmp.resize(length);

    if(length > 0) {
      const size_t len = UTF8toUTF16(s, length, &tmp[0], tmp.size());
      data = tmp.substr(0, len);
    }
  }
The same with the function copyFromLatin() adn copyFromUTF16().
This is my personal opinion and thanks for your reply.
With kind regards.

**Comment by TsudaKageyu** [comment]
I think that modifying ```String``` class is not the best solution. However, I admit my patch is still somewhat inefficient and we have some room to improve it further.
I'm going to think again how to improve it.

**Comment by TsudaKageyu** [comment]
Hi @JohnCheNey, I have just committed a new patch.

It still takes 8MB of memory while parsing the APE tag of your file, since we need to read an entire APE tag to parse it. But the memory will be freed immediately after the tag is parsed.
![memory](https://cloud.githubusercontent.com/assets/2161941/12756339/aec68326-ca16-11e5-88c5-d93011d5c045.png)

I hope it will help you.

**Comment by JohnCheNey** [comment]
It works,thank you very much.
